apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongoxp
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /home/nuc/xp/lm/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: tier
          operator: In
          values:
          - manager
---          
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-manager-jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: storage-jupyter
